package com.gemhaven.service;

import com.gemhaven.model.Auction;
import com.gemhaven.model.Bid;
import com.gemhaven.model.User;
import com.gemhaven.repository.AuctionRepository;
import com.gemhaven.repository.BidRepository;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Service
public class BiddingService {

    private final BidRepository bidRepository;
    private final AuctionRepository auctionRepository;

    public BiddingService(BidRepository bidRepository, AuctionRepository auctionRepository) {
        this.bidRepository = bidRepository;
        this.auctionRepository = auctionRepository;
    }

    /**
     * @Transactional ensures that bid placement and auction price updates happen as a single atomic unit.
     */
    @Transactional
    public Bid placeNewBid(User user, Long auctionId, BigDecimal bidAmount) {
        Auction auction = auctionRepository.findById(auctionId)
            .orElseThrow(() -> new IllegalArgumentException("Auction not found"));

        if (LocalDateTime.now().isAfter(auction.getEndTime())) {
            throw new IllegalStateException("Auction has ended.");
        }

        BigDecimal currentMax = auction.getCurrentBid() != null ? auction.getCurrentBid() : auction.getStartingPrice();
        if (bidAmount.compareTo(currentMax) <= 0) {
            throw new IllegalArgumentException("Bid amount must be strictly greater than the current top bid or starting price.");
        }

        // 1. Create and save the new bid
        Bid bid = new Bid();
        bid.setAuction(auction);
        bid.setUser(user);
        bid.setAmount(bidAmount);
        // The timestamp will be generated by the DB default CURRENT_TIMESTAMP as mapped in schema.sql
        bidRepository.save(bid);

        // 2. Update the auction's current max bid price
        auction.setCurrentBid(bidAmount);
        auctionRepository.save(auction);
        
        return bid;
    }
}
