spring.application.name=gemhaven-backend

# PostgreSQL Connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/gemhaven_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Wait to load SQL since the table might be overwritten
spring.jpa.hibernate.ddl-auto=validate

# Spring Boot will automatically execute schema.sql and data.sql on startup if this is set
spring.sql.init.mode=always
spring.sql.init.platform=postgres
