-- schema.sql is ARCHIVED.
-- DDL is now managed by Hibernate (spring.jpa.hibernate.ddl-auto=update).
-- This file is kept for reference only and is NOT executed on startup
-- (spring.sql.init.mode=never).
--
-- For production, replace Hibernate DDL management with Flyway or Liquibase migrations.
